name: Change Champion

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]
  push:
    branches: [ main ]
    paths:
      - '.changes/*.md'
      - '!.changes/README.md'
  workflow_dispatch:

jobs:
  change-champion:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true

      - uses: change-champion/action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
